// Error codes and their HTTP status (Batch 1 §8.2).

export const ERROR_STATUS = {
  VALIDATION_ERROR: 400,
  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  FORBIDDEN_ORIGIN: 403,
  NOT_FOUND: 404,
  ORDER_NOT_FOUND: 404,
  ORDERS_PAUSED: 409,
  SLOT_CLOSED: 409,
  LOCATION_UNAVAILABLE: 409,
  EXPRESS_UNAVAILABLE: 409,
  ITEM_UNAVAILABLE: 409,
  OUT_OF_STOCK: 409,
  PRICE_CHANGED: 409,
  IDEMPOTENCY_CONFLICT: 409,
  INVALID_TRANSITION: 409,
  STOCK_BELOW_SOLD: 409,
  DUPLICATE: 409,
  TOO_MANY_OPEN_ORDERS: 429,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
} as const;

export type ErrorCode = keyof typeof ERROR_STATUS;

export function statusForCode(code: ErrorCode): number {
  return ERROR_STATUS[code];
}
