// Every customer- and vendor-facing string lives here so the owner can review the wording in
// one place (Batch 1 §10.4). Brand name is spelled as on the logo: "Centre".

export const copy = {
  brand: 'Bunty Biryani Centre',

  customer: {
    menu: {
      title: "Today's menu",
      subline: (date: string) => `Today's menu · ${date}`,
      loadErrorTitle: "Couldn't load today's menu.",
      loadErrorMessage: 'Check your connection and try again.',
      emptyTitle: "Today's menu isn't up yet.",
      emptyMessage: 'Please check back soon.',
      allSoldOut: "Everything's sold out for today. See you tomorrow!",
      paused: 'Orders are temporarily paused. Please check again shortly.',
      soldOutHeading: 'Sold out',
      soldOutChip: 'Sold out',
      add: 'Add',
      onlyLeft: (n: number) => `Only ${n} left`,
      maxPerOrder: (n: number) => `Max ${n} per order`,
      addLabel: (name: string) => `Add ${name}`,
      decrementLabel: (name: string) => `Remove one ${name}`,
      incrementLabel: (name: string) => `Add one more ${name}`,
    },

    cart: {
      itemCount: (n: number) => (n === 1 ? '1 item' : `${n} items`),
      checkout: 'Checkout',
      checkoutLabel: (items: string, total: string) => `Checkout, ${items}, ${total}`,
      paused: 'Orders are paused',
      dismiss: 'Dismiss',
      lineCap: (n: number) => `You can order up to ${n} different items at once.`,
      clearedOldDay: 'Your cart from yesterday was cleared.',
      removedUnavailable: (name: string) =>
        `${name} is no longer available and was removed from your cart.`,
      removedSoldOut: (name: string) => `${name} just sold out and was removed from your cart.`,
      capped: (n: number, name: string) => `Only ${n} ${name} left. We've updated your cart.`,
    },

    checkout: {
      title: 'Checkout',
      back: 'Menu',
      cartEmpty: 'Your cart is empty.',
      orderHeading: 'Your order',
      food: 'Food',
      methodHeading: 'Delivery method',
      batchTitle: 'Batch Delivery',
      batchLines: ['Regular delivery', 'Choose location and fixed delivery slot'],
      expressTitle: 'Express Delivery',
      expressEta: (eta: string) => `Delivered in approximately ${eta}`,
      expressFee: (fee: string) => `+${fee} delivery charge`,
      expressUnavailable: 'Express delivery is currently unavailable.',
      expressHours: (hours: string) => `Express delivery runs ${hours}.`,
      noBatchOpen: 'No batch deliveries are open right now.',
      nothingOpen: 'No deliveries are open right now. Please check again later.',
      paused: 'Orders are temporarily paused. Please check again shortly.',
      optionsError: "Couldn't load delivery options.",
      whereWhenHeading: 'Where & when',
      slotTitle: (location: string, time: string) => `${location} — ${time}`,
      orderBy: (time: string) => `Order by ${time}`,
      orderWithin: (minutes: number) => `Order in the next ${minutes} min`,
      slotClosed: 'Orders for this delivery slot are closed.',
      slotClosedToday: 'No delivery on this slot today.',
      batchClosedExpressOpen: (location: string) =>
        `Batch orders for ${location} are closed. Express delivery is available.`,
      tryExpress: 'Try Express Delivery',
      slotJustClosed: (slot: string) => `Orders for ${slot} just closed.`,
      expressInfo: (eta: string, fee: string) =>
        `Delivered in approximately ${eta} · +${fee} delivery charge`,
      detailsHeading: 'Your details',
      name: 'Name',
      phone: 'Mobile number',
      phonePlaceholder: '10-digit mobile number',
      address: 'Room / address (optional)',
      addressHintBatch: 'Hostel block, room number or a landmark',
      addressHintExpress: 'Room number or a landmark helps us find you quickly.',
      addressCount: (count: number, max: number) => `${count}/${max}`,
      forget: 'Not you? Clear details',
      summaryHeading: 'Summary',
      deliveryBatch: 'Delivery · Batch',
      deliveryExpress: 'Delivery · Express',
      free: 'Free',
      total: 'Total',
      batchLine: (location: string, time: string) => `${location} · Today, ${time}`,
      expressLine: (location: string, eta: string) => `Express to ${location} · approx. ${eta}`,
      payment: 'Payment: CASH ON DELIVERY',
      payInCash: (total: string) => `Pay ${total} in cash when your food arrives.`,
      placeOrder: (total: string) => `Place order · ${total}`,
      pausedButton: 'Orders are paused',
      // Batch 4 only: Batch 5 sends the request and removes this.
      notSent:
        "Your order is ready, but online ordering isn't switched on yet. Nothing has been sent.",
      needMethod: 'Choose a delivery method',
      needSlot: 'Choose a delivery slot',
      needLocation: 'Choose where to deliver',
    },
  },

  deliverySummary: {
    batch: (slots: string) => `Batch: ${slots}`,
    batchClosed: 'Batch: closed for today',
    slot: (location: string, time: string) => `${location} ${time}`,
    express: (min: number, max: number, fee: string) =>
      `Express approx. ${min}–${max} min (+${fee})`,
  },

  common: {
    tryAgain: 'Try again',
    loading: 'Loading…',
    notFoundTitle: 'Page not found',
    notFoundMessage: "We couldn't find that page.",
    backToMenu: 'Back to the menu',
    genericError: 'Something went wrong. Please try again.',
    networkError: "Couldn't reach the server. Check your connection.",
  },

  admin: {
    shellTitle: 'BBC ADMIN',
    logout: 'Log out',
    loggingOut: 'Logging out…',
    todayPlaceholder: 'Dashboard arrives in Batch 6.',
    sessionLoadError: "Couldn't check your login.",
    tabs: { today: 'Today', stock: 'Stock', menu: 'Menu', settings: 'Settings' },
    login: {
      title: 'VENDOR LOGIN',
      username: 'Username',
      password: 'Password',
      showPassword: 'Show password',
      submit: 'Log in',
      submitting: 'Logging in…',
      usernameRequired: 'Enter your username',
      passwordRequired: 'Enter your password',
      invalidCredentials: 'Wrong username or password.',
      rateLimited: 'Too many attempts. Try again in a few minutes.',
      network: "Couldn't reach the server. Check your connection.",
    },
  },
} as const;
